apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "gke-web-ingress"
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: fe-secret
  rules:
  - host: server.domain.com  
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: fe-srv
            port:
              number: 8000
  - host: grpcweb.domain.com  
    http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: be-srv
            port:
              number: 18080
  # - host: grpc.domain.com  
  #   http:
  #     paths:
  #     - path: /*
  #       pathType: Prefix
  #       backend:
          # service:
          #   name: be-srv-grpc
          #   port:
          #     number: 50051  

