---
apiVersion: v1
kind: Service
metadata:
  name: be-srv
  labels:
    type: be-srv
  annotations:
    cloud.google.com/app-protocols: '{"be":"HTTP2"}'
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"18080":{}}}'  
    cloud.google.com/backend-config: '{"default": "be-envoy-backendconfig"}'    
spec:
  type: NodePort 
  ports:
  - name: be
    port: 18080
    protocol: TCP
    targetPort: 18080   
  selector:
    app: be
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: be-envoy-backendconfig
spec:
  healthCheck:
    type: HTTPS
    requestPath: /healthz
    port: 18081